const br = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const n2 = x=>Number(x??0).toFixed(2);
function taxaMensalEfetiva(a){return Math.pow(1+(a||0),1/12)-1;}
function prestacaoPrice(saldo,i,n){if(saldo<=0||i<=0||n<=0)return 0;return saldo*i/(1-Math.pow(1+i,-n));}
function addMonths(d,n){const dt=new Date(d);dt.setMonth(dt.getMonth()+n);return dt;}
const extrasPontuais=[];let appliedExtraMensal=0;
function calcBases(){let saldo=parseFloat(saldoEl.value),ta=parseFloat(taxaEl.value),prazo=parseInt(prazoEl.value),seg=parseFloat(segEl.value),tx=parseFloat(txEl.value);let i=taxaMensalEfetiva(ta);let pBase=prestacaoPrice(saldo,i,prazo);prestBaseEl.value=n2(pBase);prestTotEl.value=n2(pBase+seg+tx);sugEl.value=n2(extraParaMeta(saldo,i,pBase,60));return{saldo,i,prazo,pBase};}
function extraParaMeta(saldo,i,pBase,n){let low=0,high=saldo,ans=0;for(let k=0;k<60;k++){let mid=(low+high)/2,s=saldo;for(let m=0;m<n&&s>0;m++){let j=s*i;let a=pBase-j;s-=a+mid;}if(s>0)low=mid;else{ans=mid;high=mid;}}return ans;}
function sim(){let {saldo,i,prazo,pBase}=calcBases();let data=new Date(dataEl.value+'T00:00:00');let linhas=[],m=0;let mapa=new Map();extrasPontuais.forEach(e=>mapa.set(e.data,(mapa.get(e.data)||0)+e.valor));while(saldo>0&&m<2000){m++;let j=saldo*i;let a=pBase-j;let d=data.toISOString().slice(0,10);let ep=mapa.get(d)||0;let extra=appliedExtraMensal+ep;saldo-=a+extra;if(saldo<0)saldo=0;linhas.push({m,d,pBase,extraMensal:appliedExtraMensal,extraPontual:ep,juros:j,amort:a,total:a+extra,saldo});data=addMonths(data,1);}let totJ=linhas.reduce((s,l)=>s+l.juros,0),totP=linhas.reduce((s,l)=>s+l.pBase,0),totE=linhas.reduce((s,l)=>s+l.extraMensal+l.extraPontual,0);return{linhas,prazo:m,totJ,totP,totE};}
function preencher(r){let tb=document.querySelector('#tabela tbody');tb.innerHTML='';r.linhas.forEach(l=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${l.m}</td><td>${l.d}</td><td>${br.format(l.pBase)}</td><td>${br.format(l.extraMensal)}</td><td>${br.format(l.extraPontual)}</td><td>${br.format(l.juros)}</td><td>${br.format(l.amort)}</td><td>${br.format(l.total)}</td><td>${br.format(l.saldo)}</td>`;tb.appendChild(tr);});prazoOut.textContent=r.prazo+' meses';totJ.textContent=br.format(r.totJ);totPrest.textContent=br.format(r.totP);totExtras.textContent=br.format(r.totE);}
function atualizar(){preencher(sim());}
function confirmarMensal(){appliedExtraMensal=parseFloat(extraMensalInput.value)||0;msgMensal.style.display='block';setTimeout(()=>msgMensal.style.display='none',1500);atualizar();}
function limparMensal(){appliedExtraMensal=0;atualizar();}
function confirmarPontual(){let d=dataPontual.value,v=parseFloat(valorPontual.value)||0;if(!d)return;extrasPontuais.push({data:d,valor:v});msgPontual.style.display='block';setTimeout(()=>msgPontual.style.display='none',1500);atualizar();renderLista();}
function renderLista(){listaPontuais.innerHTML=extrasPontuais.map((e,i)=>`${e.data} — ${br.format(e.valor)} <button onclick='remPont(${i})'>remover</button>`).join('<br>');}
function remPont(i){extrasPontuais.splice(i,1);atualizar();renderLista();}
function exportCSV(){let r=sim();let rows=[['#','Data','Prestação','Extra Mensal','Extra Pontual','Juros','Amortização','Total Amortizado','Saldo'].join(',')];r.linhas.forEach(l=>rows.push([l.m,l.d,n2(l.pBase),n2(l.extraMensal),n2(l.extraPontual),n2(l.juros),n2(l.amort),n2(l.total),n2(l.saldo)].join(',')));let blob=new Blob([rows.join('\\n')],{type:'text/csv'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Amortizacao_v14.csv';a.click();}
const saldoEl=document.getElementById('saldo'),taxaEl=document.getElementById('taxaEfetiva'),prazoEl=document.getElementById('prazo'),segEl=document.getElementById('seguro'),txEl=document.getElementById('taxaOp'),dataEl=document.getElementById('dataInicio');const prestBaseEl=document.getElementById('prestacaoBase'),prestTotEl=document.getElementById('prestacaoTotal'),sugEl=document.getElementById('sugestao'),prazoOut=document.getElementById('prazoOut'),totJ=document.getElementById('totJuros'),totPrest=document.getElementById('totPrest'),totExtras=document.getElementById('totExtras');window.onload=()=>{atualizar();renderLista();};
